import type { ExerciseSeed } from './types';

/** Biblioteca inicial de ejercicios. */
export const exerciseSeeds: ExerciseSeed[] = [
  // ── Pecho (chest) ───────────────────────────────────────────────────────
  { slug: 'press-banca-plano-barra', name: 'Press de banca plano con barra', muscleGroup: 'chest', equipment: 'barbell' },
  { slug: 'press-banca-inclinado-barra', name: 'Press de banca inclinado con barra', muscleGroup: 'chest', equipment: 'barbell' },
  { slug: 'press-banca-declinado-barra', name: 'Press de banca declinado con barra', muscleGroup: 'chest', equipment: 'barbell' },
  { slug: 'press-plano-mancuernas', name: 'Press plano con mancuernas', muscleGroup: 'chest', equipment: 'dumbbell' },
  { slug: 'press-inclinado-mancuernas', name: 'Press inclinado con mancuernas', muscleGroup: 'chest', equipment: 'dumbbell' },
  { slug: 'aperturas-planas-mancuernas', name: 'Aperturas planas con mancuernas', muscleGroup: 'chest', equipment: 'dumbbell' },
  { slug: 'aperturas-inclinadas-mancuernas', name: 'Aperturas inclinadas con mancuernas', muscleGroup: 'chest', equipment: 'dumbbell' },
  { slug: 'cruces-polea-alta', name: 'Cruces en polea alta', muscleGroup: 'chest', equipment: 'cable' },
  { slug: 'cruces-polea-baja', name: 'Cruces en polea baja', muscleGroup: 'chest', equipment: 'cable' },
  { slug: 'aperturas-maquina-pec-deck', name: 'Aperturas en máquina (pec deck)', muscleGroup: 'chest', equipment: 'machine' },
  { slug: 'press-pecho-maquina', name: 'Press de pecho en máquina', muscleGroup: 'chest', equipment: 'machine' },
  { slug: 'press-banca-smith', name: 'Press de banca en máquina Smith', muscleGroup: 'chest', equipment: 'machine' },
  { slug: 'fondos-paralelas-pecho', name: 'Fondos en paralelas (énfasis pecho)', muscleGroup: 'chest', equipment: 'bodyweight' },
  { slug: 'flexiones-brazos', name: 'Flexiones de brazos', muscleGroup: 'chest', equipment: 'bodyweight' },
  { slug: 'flexiones-declinadas', name: 'Flexiones declinadas', muscleGroup: 'chest', equipment: 'bodyweight' },
  { slug: 'flexiones-con-banda', name: 'Flexiones con banda elástica', muscleGroup: 'chest', equipment: 'band' },

  // ── Espalda (back) ──────────────────────────────────────────────────────
  { slug: 'dominadas-pronas', name: 'Dominadas pronas', muscleGroup: 'back', equipment: 'bodyweight' },
  { slug: 'dominadas-supinas', name: 'Dominadas supinas (chin-up)', muscleGroup: 'back', equipment: 'bodyweight' },
  { slug: 'dominadas-agarre-neutro', name: 'Dominadas con agarre neutro', muscleGroup: 'back', equipment: 'bodyweight' },
  { slug: 'dominadas-asistidas-maquina', name: 'Dominadas asistidas en máquina', muscleGroup: 'back', equipment: 'machine' },
  { slug: 'jalon-al-pecho', name: 'Jalón al pecho en polea', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'jalon-agarre-supino', name: 'Jalón al pecho con agarre supino', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'jalon-tras-nuca', name: 'Jalón tras nuca', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'jalon-brazos-rigidos', name: 'Jalón con brazos rígidos (pullover en polea)', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'remo-barra', name: 'Remo inclinado con barra', muscleGroup: 'back', equipment: 'barbell' },
  { slug: 'remo-pendlay', name: 'Remo Pendlay', muscleGroup: 'back', equipment: 'barbell' },
  { slug: 'remo-mancuerna-una-mano', name: 'Remo con mancuerna a una mano', muscleGroup: 'back', equipment: 'dumbbell' },
  { slug: 'remo-sentado-polea', name: 'Remo sentado en polea', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'remo-maquina-apoyo-pecho', name: 'Remo en máquina con apoyo al pecho', muscleGroup: 'back', equipment: 'machine' },
  { slug: 'remo-t-barra', name: 'Remo T con barra', muscleGroup: 'back', equipment: 'barbell' },
  { slug: 'remo-sello-barra', name: 'Remo sello con barra (seal row)', muscleGroup: 'back', equipment: 'barbell' },
  { slug: 'remo-invertido', name: 'Remo invertido', muscleGroup: 'back', equipment: 'bodyweight' },
  { slug: 'remo-con-banda', name: 'Remo con banda elástica', muscleGroup: 'back', equipment: 'band' },
  { slug: 'pullover-mancuerna', name: 'Pullover con mancuerna', muscleGroup: 'back', equipment: 'dumbbell' },
  { slug: 'face-pull-polea', name: 'Face pull en polea', muscleGroup: 'back', equipment: 'cable' },
  { slug: 'hiperextensiones-banco-romano', name: 'Hiperextensiones en banco romano', muscleGroup: 'back', equipment: 'bodyweight' },

  // ── Piernas (legs) ──────────────────────────────────────────────────────
  { slug: 'sentadilla-trasera-barra', name: 'Sentadilla trasera con barra', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'sentadilla-frontal-barra', name: 'Sentadilla frontal con barra', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'sentadilla-goblet', name: 'Sentadilla goblet con mancuerna', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'sentadilla-bulgara', name: 'Sentadilla búlgara con mancuernas', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'sentadilla-hack-maquina', name: 'Sentadilla hack en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'sentadilla-smith', name: 'Sentadilla en máquina Smith', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'sentadilla-peso-corporal', name: 'Sentadilla con peso corporal', muscleGroup: 'legs', equipment: 'bodyweight' },
  { slug: 'sentadilla-con-salto', name: 'Sentadilla con salto', muscleGroup: 'legs', equipment: 'bodyweight' },
  { slug: 'peso-muerto-convencional', name: 'Peso muerto convencional', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'peso-muerto-rumano', name: 'Peso muerto rumano', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'peso-muerto-sumo', name: 'Peso muerto sumo', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'peso-muerto-piernas-rigidas', name: 'Peso muerto con piernas rígidas', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'peso-muerto-rumano-mancuernas', name: 'Peso muerto rumano con mancuernas', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'prensa-piernas-45', name: 'Prensa de piernas 45°', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'zancadas-mancuernas', name: 'Zancadas con mancuernas', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'zancadas-caminando-barra', name: 'Zancadas caminando con barra', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'zancadas-inversas-mancuernas', name: 'Zancadas inversas con mancuernas', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'subida-cajon-mancuernas', name: 'Subida al cajón con mancuernas', muscleGroup: 'legs', equipment: 'dumbbell' },
  { slug: 'extensiones-cuadriceps-maquina', name: 'Extensiones de cuádriceps en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'curl-femoral-acostado-maquina', name: 'Curl femoral acostado en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'curl-femoral-sentado-maquina', name: 'Curl femoral sentado en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'curl-nordico', name: 'Curl nórdico', muscleGroup: 'legs', equipment: 'bodyweight' },
  { slug: 'hip-thrust-barra', name: 'Hip thrust con barra', muscleGroup: 'legs', equipment: 'barbell' },
  { slug: 'puente-gluteos', name: 'Puente de glúteos', muscleGroup: 'legs', equipment: 'bodyweight' },
  { slug: 'patada-gluteo-polea', name: 'Patada de glúteo en polea', muscleGroup: 'legs', equipment: 'cable' },
  { slug: 'elevacion-gemelos-pie', name: 'Elevación de gemelos de pie', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'elevacion-gemelos-sentado', name: 'Elevación de gemelos sentado', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'aductores-maquina', name: 'Aductores en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'abductores-maquina', name: 'Abductores en máquina', muscleGroup: 'legs', equipment: 'machine' },
  { slug: 'buenos-dias-barra', name: 'Buenos días con barra', muscleGroup: 'legs', equipment: 'barbell' },

  // ── Hombros (shoulders) ─────────────────────────────────────────────────
  { slug: 'press-militar-pie-barra', name: 'Press militar de pie con barra', muscleGroup: 'shoulders', equipment: 'barbell' },
  { slug: 'press-militar-sentado-barra', name: 'Press militar sentado con barra', muscleGroup: 'shoulders', equipment: 'barbell' },
  { slug: 'press-hombros-mancuernas-sentado', name: 'Press de hombros con mancuernas sentado', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'press-arnold', name: 'Press Arnold', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'press-hombros-maquina', name: 'Press de hombros en máquina', muscleGroup: 'shoulders', equipment: 'machine' },
  { slug: 'push-press-barra', name: 'Push press con barra', muscleGroup: 'shoulders', equipment: 'barbell' },
  { slug: 'elevaciones-laterales-mancuernas', name: 'Elevaciones laterales con mancuernas', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'elevaciones-laterales-polea', name: 'Elevaciones laterales en polea', muscleGroup: 'shoulders', equipment: 'cable' },
  { slug: 'elevaciones-laterales-banda', name: 'Elevaciones laterales con banda', muscleGroup: 'shoulders', equipment: 'band' },
  { slug: 'elevaciones-frontales-mancuernas', name: 'Elevaciones frontales con mancuernas', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'pajaros-mancuernas', name: 'Elevaciones posteriores (pájaros) con mancuernas', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'vuelos-posteriores-maquina', name: 'Vuelos posteriores en máquina (pec deck inverso)', muscleGroup: 'shoulders', equipment: 'machine' },
  { slug: 'remo-al-menton-barra', name: 'Remo al mentón con barra', muscleGroup: 'shoulders', equipment: 'barbell' },
  { slug: 'encogimientos-mancuernas', name: 'Encogimientos de hombros con mancuernas', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { slug: 'encogimientos-barra', name: 'Encogimientos de hombros con barra', muscleGroup: 'shoulders', equipment: 'barbell' },

  // ── Brazos (arms) ───────────────────────────────────────────────────────
  { slug: 'curl-biceps-barra', name: 'Curl de bíceps con barra', muscleGroup: 'arms', equipment: 'barbell' },
  { slug: 'curl-biceps-barra-w', name: 'Curl de bíceps con barra W', muscleGroup: 'arms', equipment: 'barbell' },
  { slug: 'curl-biceps-alternado-mancuernas', name: 'Curl de bíceps alternado con mancuernas', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'curl-martillo-mancuernas', name: 'Curl martillo con mancuernas', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'curl-predicador-barra-w', name: 'Curl predicador con barra W (banco Scott)', muscleGroup: 'arms', equipment: 'barbell' },
  { slug: 'curl-concentrado', name: 'Curl concentrado con mancuerna', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'curl-biceps-polea-baja', name: 'Curl de bíceps en polea baja', muscleGroup: 'arms', equipment: 'cable' },
  { slug: 'curl-inclinado-mancuernas', name: 'Curl inclinado con mancuernas', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'curl-biceps-banda', name: 'Curl de bíceps con banda elástica', muscleGroup: 'arms', equipment: 'band' },
  { slug: 'press-frances-barra-w', name: 'Press francés con barra W', muscleGroup: 'arms', equipment: 'barbell' },
  { slug: 'extensiones-triceps-polea-alta', name: 'Extensiones de tríceps en polea alta', muscleGroup: 'arms', equipment: 'cable' },
  { slug: 'extensiones-triceps-soga-polea', name: 'Extensiones de tríceps con soga en polea', muscleGroup: 'arms', equipment: 'cable' },
  { slug: 'extensiones-triceps-banda', name: 'Extensiones de tríceps con banda', muscleGroup: 'arms', equipment: 'band' },
  { slug: 'patada-triceps-mancuerna', name: 'Patada de tríceps con mancuerna', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'press-banca-agarre-cerrado', name: 'Press de banca con agarre cerrado', muscleGroup: 'arms', equipment: 'barbell' },
  { slug: 'extension-triceps-sobre-cabeza-mancuerna', name: 'Extensión de tríceps sobre la cabeza con mancuerna', muscleGroup: 'arms', equipment: 'dumbbell' },
  { slug: 'fondos-entre-bancos', name: 'Fondos entre bancos', muscleGroup: 'arms', equipment: 'bodyweight' },
  { slug: 'fondos-paralelas-triceps', name: 'Fondos en paralelas (énfasis tríceps)', muscleGroup: 'arms', equipment: 'bodyweight' },
  { slug: 'flexiones-diamante', name: 'Flexiones diamante', muscleGroup: 'arms', equipment: 'bodyweight' },

  // ── Core ────────────────────────────────────────────────────────────────
  { slug: 'plancha-frontal', name: 'Plancha frontal', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'plancha-lateral', name: 'Plancha lateral', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'plancha-toques-hombro', name: 'Plancha con toques de hombro', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'crunch-abdominal', name: 'Crunch abdominal', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'crunch-polea-alta', name: 'Crunch en polea alta', muscleGroup: 'core', equipment: 'cable' },
  { slug: 'crunch-bicicleta', name: 'Crunch bicicleta', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'elevaciones-piernas-colgado', name: 'Elevaciones de piernas colgado', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'elevaciones-piernas-acostado', name: 'Elevaciones de piernas acostado', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'rueda-abdominal', name: 'Rueda abdominal', muscleGroup: 'core', equipment: 'other' },
  { slug: 'pallof-press-polea', name: 'Pallof press en polea', muscleGroup: 'core', equipment: 'cable' },
  { slug: 'russian-twist', name: 'Russian twist', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'dead-bug', name: 'Dead bug', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'bird-dog', name: 'Bird dog', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'mountain-climbers', name: 'Mountain climbers', muscleGroup: 'core', equipment: 'bodyweight' },
  { slug: 'lenador-polea', name: 'Leñador en polea (woodchopper)', muscleGroup: 'core', equipment: 'cable' },

  // ── Cuerpo completo (full_body) ─────────────────────────────────────────
  { slug: 'burpees', name: 'Burpees', muscleGroup: 'full_body', equipment: 'bodyweight' },
  { slug: 'cargada-y-press-barra', name: 'Cargada y press con barra (clean & press)', muscleGroup: 'full_body', equipment: 'barbell' },
  { slug: 'arranque-barra', name: 'Arranque con barra (snatch)', muscleGroup: 'full_body', equipment: 'barbell' },
  { slug: 'cargada-potencia-barra', name: 'Cargada de potencia con barra (power clean)', muscleGroup: 'full_body', equipment: 'barbell' },
  { slug: 'kettlebell-swing', name: 'Kettlebell swing', muscleGroup: 'full_body', equipment: 'other' },
  { slug: 'thruster-barra', name: 'Thruster con barra', muscleGroup: 'full_body', equipment: 'barbell' },
  { slug: 'caminata-granjero', name: "Caminata del granjero (farmer's walk)", muscleGroup: 'full_body', equipment: 'dumbbell' },
  { slug: 'wall-ball', name: 'Wall ball', muscleGroup: 'full_body', equipment: 'other' },
  { slug: 'turkish-get-up', name: 'Turkish get-up', muscleGroup: 'full_body', equipment: 'other' },

  // ── Cardio ──────────────────────────────────────────────────────────────
  { slug: 'caminata-cinta', name: 'Caminata en cinta', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'correr-cinta', name: 'Correr en cinta', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'bicicleta-fija', name: 'Bicicleta fija', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'eliptico', name: 'Elíptico', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'remo-ergometro', name: 'Remo ergómetro', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'escalador', name: 'Escalador (stairmaster)', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'bicicleta-aire', name: 'Bicicleta de aire (assault bike)', muscleGroup: 'cardio', equipment: 'machine' },
  { slug: 'saltar-soga', name: 'Saltar la soga', muscleGroup: 'cardio', equipment: 'other' },
  { slug: 'natacion', name: 'Natación', muscleGroup: 'cardio', equipment: 'other' },
  { slug: 'ciclismo-ruta', name: 'Ciclismo en ruta', muscleGroup: 'cardio', equipment: 'other' },
  { slug: 'running-exterior', name: 'Running exterior', muscleGroup: 'cardio', equipment: 'other' },
  { slug: 'caminata-exterior', name: 'Caminata exterior', muscleGroup: 'cardio', equipment: 'other' },
  { slug: 'hiit-generico', name: 'HIIT (intervalos de alta intensidad)', muscleGroup: 'cardio', equipment: 'bodyweight' },
];
